### ISSUE TITLE
sideberry shrinks the page on hover

### ISSUE THREAD

**Issue by ecribia** [scientiac/scifox#7]
After a recent update, the webpages now shrinks whenever i hover over sideberry. Is there a way to make it work like a overlay instead?

Thanks for all your work! :)

**Comment by scientiac** [comment]
https://github.com/scientiac/scifox/pull/6

We have fixed the issue already. Did it break again? 

Can you share your Firefox version?

**Comment by ecribia** [comment]
Sorry, I should have mentioned that im using the userChrome file from the immersive branch.

I just tried the main branch, and it seems to work as expected, but im not sure on how to translate this to the immersive branch?

Im using Firefox 141.0

**Comment by scientiac** [comment]
https://github.com/scientiac/scifox/commit/a187817dcffce97bc8e83ce6d9ed496df881c01e

Both the versions were fixed at the same time.

**Comment by ecribia** [comment]
̶ ̶W̶o̶w̶,̶ ̶d̶o̶n̶'̶t̶ ̶k̶n̶o̶w̶ ̶h̶o̶w̶ ̶i̶ ̶m̶i̶s̶s̶e̶d̶ ̶t̶h̶a̶t̶ ̶t̶h̶e̶ ̶f̶i̶r̶s̶t̶ ̶t̶i̶m̶e̶ ̶i̶ ̶c̶h̶e̶c̶k̶e̶d̶.̶ ̶M̶y̶ ̶a̶p̶o̶l̶o̶g̶i̶e̶s̶ ̶

Edit: Upon restart, the issue is not resolved. The resize issue is still there even after i updated it.

**Comment by scientiac** [comment]
Here is the userchrome I am using:
```css
/*
┏━╸┏━┓┏┓╻┏━╸╻┏━╸╻ ╻┏━┓┏━┓╺┳╸╻┏━┓┏┓╻
┃  ┃ ┃┃┗┫┣╸ ┃┃╺┓┃ ┃┣┳┛┣━┫ ┃ ┃┃ ┃┃┗┫
┗━╸┗━┛╹ ╹╹  ╹┗━┛┗━┛╹┗╸╹ ╹ ╹ ╹┗━┛╹ ╹
*/

/*
┏━┓╻╺┳┓┏━╸┏┓ ┏━╸┏━┓╻ ╻
┗━┓┃ ┃┃┣╸ ┣┻┓┣╸ ┣┳┛┗┳┛
┗━┛╹╺┻┛┗━╸┗━┛┗━╸╹┗╸ ╹
*/
#sidebar-box #sidebar-header {
  visibility: collapse;
}

#sidebar-box {
  --uc-sidebar-width: 10px !important;
  --uc-sidebar-hover-width: 275px;
  --uc-autohide-sidebar-delay: 1s;
  position: relative;
  min-width: var(--uc-sidebar-width) !important;
  width: var(--uc-sidebar-width) !important;
  max-width: var(--uc-sidebar-width) !important;
  z-index:3;
}

#sidebar {
  transition: min-width 400ms linear var(--uc-autohide-sidebar-delay), 
              opacity 400ms ease calc(var(--uc-autohide-sidebar-delay) + 100ms) !important;
  min-width: var(--uc-sidebar-width) !important;
  opacity: 0 !important;
  will-change: min-width, opacity;
}

#sidebar:hover {
  min-width: var(--uc-sidebar-hover-width) !important;
  opacity: 1 !important;
  transition-delay: 0s !important;
}

#sidebar-box > #sidebar-splitter, 
#sidebar-splitter {
    display: none;
}

#sidebar-box {
  background: var(--lwt-accent-color) !important;
}

/*
┏━┓┏━┓╺┳┓╺┳┓╻┏┓╻┏━╸
┣━┛┣━┫ ┃┃ ┃┃┃┃┗┫┃╺┓
╹  ╹ ╹╺┻┛╺┻┛╹╹ ╹┗━┛
┏━┓╻ ╻┏━┓┏━┓┏━┓╻ ╻┏┓╻╺┳┓
┗━┓┃ ┃┣┳┛┣┳┛┃ ┃┃ ┃┃┗┫ ┃┃
┗━┛┗━┛╹┗╸╹┗╸┗━┛┗━┛╹ ╹╺┻┛
*/

@media not all and (display-mode: fullscreen) {
  #appcontent .browserStack,
  #browser,
  .browserContainer {
    background: var(--lwt-accent-color)
  }

  #browser > #appcontent {
    --margin: 10px;  

    margin-left: 0px;
    margin-right: var(--margin);
    margin-top: 0px;
    margin-bottom: var(--margin);
  
    browser {
      --outline: 1px solid var(--arrowpanel-background);
      border: var(--outline);
    }
  }
}

/*
┏━╸┏━┓┏┓╻╺┳╸┏━╸╻ ╻╺┳╸
┃  ┃ ┃┃┗┫ ┃ ┣╸ ┏╋┛ ┃
┗━╸┗━┛╹ ╹ ╹ ┗━╸╹ ╹ ╹
┏┳┓┏━╸┏┓╻╻ ╻
┃┃┃┣╸ ┃┗┫┃ ┃
╹ ╹┗━╸╹ ╹┗━┛
*/

#toolbar-menubar menupopup,
#toolbar-context-menu,
#toolbar-context-menu menupopup,
#unified-extensions-context-menu,
#unified-extensions-context-menu menupopup,
#placesContext, #placesContext menupopup,
#downloadsContextMenu, #downloadsContextMenu menupopup,
#sidebarMenu-popup, #PopupSearchAutoComplete,
:is(#back-button, #forward-button) menupopup,
#permission-popup-menulist menupopup,
#contentAreaContextMenu[showservicesmenu="true"],
#contentAreaContextMenu[showservicesmenu="true"] menupopup {
  --panel-background: var(--arrowpanel-background) !important;
  --panel-border-color: var(--toolbar-bgcolor) !important;
  --toolbar-field-focus-background-color: var(--toolbarbutton-icon-fill) !important;
  --panel-color: var(--toolbarbutton-icon-fill) !important;

  menu:where([_moz-menuactive="true"]:not([disabled="true"])), 
  menuitem:where([_moz-menuactive="true"]:not([disabled="true"])) {
    background-color: var(--arrowpanel-dimmed) !important;
    color: var(--toolbarbutton-icon-fill) !important;
  }
  
  menu:where([_moz-menuactive="true"][disabled="true"]), 
  menuitem:where([_moz-menuactive="true"][disabled="true"]) {
    background-color: transparent !important;
  } 
}

/*
┏┳┓╻┏┓╻╻┏┳┓┏━┓╻
┃┃┃┃┃┗┫┃┃┃┃┣━┫┃
╹ ╹╹╹ ╹╹╹ ╹╹ ╹┗━╸
┏━╸╻ ╻╺┳╸┏━╸┏┓╻┏━┓╻┏━┓┏┓╻┏━┓
┣╸ ┏╋┛ ┃ ┣╸ ┃┗┫┗━┓┃┃ ┃┃┗┫┗━┓
┗━╸╹ ╹ ╹ ┗━╸╹ ╹┗━┛╹┗━┛╹ ╹┗━┛
┏┳┓┏━╸┏┓╻╻ ╻
┃┃┃┣╸ ┃┗┫┃ ┃
╹ ╹┗━╸╹ ╹┗━┛
 */

#unified-extensions-view{
    --uei-icon-size: 24px;
    --extensions-in-row: 4;

    width: 100% !important;
    :is(
      toolbarseparator,
      .unified-extensions-item-menu-button.subviewbutton,
      .unified-extensions-item-action-button .unified-extensions-item-contents
    ) {display: none !important;}

    :is(
      #overflowed-extensions-list,
      #unified-extensions-area,
      .unified-extensions-list 
    ){
      display: grid !important;
      grid-template-columns: repeat(var(--extensions-in-row),auto);
      justify-items: center !important;
      align-items: center !important;
    }
    
    .unified-extensions-item-action-button {padding-right: 3px !important;}
}

/*
┏━╸┏━┓┏┓╻╺┳╸┏━┓
┣╸ ┃ ┃┃┗┫ ┃ ┗━┓
╹  ┗━┛╹ ╹ ╹ ┗━┛
*/

* {
  font-family: monospace !important;
  font-size: 16px !important;
}

/*
╻ ╻╻╺┳┓╺┳┓┏━╸┏┓╻
┣━┫┃ ┃┃ ┃┃┣╸ ┃┗┫
╹ ╹╹╺┻┛╺┻┛┗━╸╹ ╹
┏┓╻┏━┓╻ ╻┏┓ ┏━┓┏━┓
┃┗┫┣━┫┃┏┛┣┻┓┣━┫┣┳┛
╹ ╹╹ ╹┗┛ ┗━┛╹ ╹╹┗╸
*/

#nav-bar:not([customizing]) {
  opacity: 0;
  min-height: 10px;
  max-height: 10px;
  transition: max-height 1s linear 3s, opacity 600ms ease 3s !important;
}

#nav-bar:hover,
#nav-bar:focus-within {
  opacity: 1;
  min-height: 10px;
  max-height: 50px;
  transition-duration: 200ms !important;
  transition-delay: 0s, 200ms !important;
}

#urlbar:not([customizing]) {
  opacity: 0;
  min-height: 10px;
  max-height: 10px;
  transition: max-height 1s linear 3s, opacity 600ms ease 3s !important;
}

#urlbar:hover,
#urlbar:focus-within {
  opacity: 1;
  min-height: 10px;
  max-height: 50px; 
  transition-duration: 200ms !important;
  transition-delay: 0s, 200ms !important;
}

#urlbar:focus-within {
  height: 0% !important;
}

.urlbar-input-container {
    height: 100% !important;
}

.urlbarView {
    background: var(--arrowpanel-background) !important;
    border-radius: 5px;
}

/* 
┏━┓┏━╸┏┳┓┏━┓╻ ╻╻┏┓╻┏━╸
┣┳┛┣╸ ┃┃┃┃ ┃┃┏┛┃┃┗┫┃╺┓
╹┗╸┗━╸╹ ╹┗━┛┗┛ ╹╹ ╹┗━┛
┏━╸┏━┓┏┳┓┏━┓┏━┓┏┓╻┏━╸┏┓╻╺┳╸┏━┓
┃  ┃ ┃┃┃┃┣━┛┃ ┃┃┗┫┣╸ ┃┗┫ ┃ ┗━┓
┗━╸┗━┛╹ ╹╹  ┗━┛╹ ╹┗━╸╹ ╹ ╹ ┗━┛
*/

/* Tabs elements  */
#TabsToolbar { display: none !important; }

#TabsToolbar .titlebar-spacer {
    display: none !important;
}

/* Titlebar Window Control Buttons */
.titlebar-buttonbox-container{ display:none }

/* Url Bar  */
#urlbar-input-container {
  border: 1px solid rgba(0, 0, 0, 0) !important;
}

#urlbar-container {
  margin: 0 !important;
  padding-block: 2px !important;
  min-height: var(--urlbar-height) !important;
}

#urlbar[focused='true'] > #urlbar-background {
  box-shadow: none !important;
}

#navigator-toolbox {
  border: none !important;
  padding: 4px !important;
}

/* Bookmarks bar  */
.bookmark-item .toolbarbutton-icon {
  display: none;
}
toolbarbutton.bookmark-item:not(.subviewbutton) {
  min-width: 1.6em;
}

/* Toolbar  */
#tracking-protection-icon-container,
#urlbar-zoom-button,
#star-button-box,
#pageActionButton,
#pageActionSeparator,
#tabs-newtab-button,
#back-button,
#forward-button,
.tab-secondary-label {
  display: none !important;
}

/* Disable elements  */
#context-pocket,
#context-sendpagetodevice,
#context-selectall,
#context-inspect-a11y,
#context-sendlinktodevice,
#context-openlinkinusercontext-menu,
#context-savelink,
#context-savelinktopocket,
#context-sendlinktodevice,
#context-sendimage,
#context-print-selection {
  display: none !important;
}

#context_bookmarkTab,
#context_moveTabOptions,
#context_sendTabToDevice,
#context_reopenInContainer,
#context_selectAllTabs,
#context_closeTabOptions {
  display: none !important;
}
```


This is what I have in my configuration. And it works. 

https://github.com/user-attachments/assets/272c5297-3e27-4199-94d8-0dfc31711812

**Comment by scientiac** [comment]
Should be fixed with #8.

**Comment by ecribia** [comment]
Can confirm that the above fix worked :) Thanks!
